[[params]]
  scheduler='none'
  optimizer='samprodigy'
  learning_rate=1e-3
  conditioning_smoother=0.9
  momentum=0.9
[[params]]
  scheduler='warmup'
  optimizer='samadam'
  learning_rate=1e-2
  conditioning_smoother=0.99
  momentum=0.9
[[params]]
  scheduler='onecycle'
  optimizer='sgd'
  learning_rate=1e-1
  conditioning_smoother=0.999
  momentum=0.9
[[params]]
  scheduler='none'
  optimizer='samprodigy'
  learning_rate=1e-3
  conditioning_smoother=0.9
  momentum=0.9
[[params]]
  scheduler='warmup'
  optimizer='samadam'
  learning_rate=1e-2
  conditioning_smoother=0.99
  momentum=0.9
[[params]]
  scheduler='onecycle'
  optimizer='sgd'
  learning_rate=1e-1
  conditioning_smoother=0.999
  momentum=0.9